### ISSUE TITLE
Getting 400 Bad Request

### ISSUE THREAD

**Issue by scottcwilson** [tokzk/jekyll-amazon#4]
Just using 

{% amazon 767913736 detail %}

and I have set the 3 environment variables. 

jekyll-amazon (0.2.1)
jekyll (3.3.1)
ruby 2.2.2p95

Specs seem to fail too.

**Comment by tokzk** [comment]
767913736 is probably ISBN.
Please use ASIN 0767913736.

**Comment by scottcwilson** [comment]
Nope - same result - 400.  Are you able to successfully run specs?

**Comment by tokzk** [comment]
> Jekyll::Amazon::AmazonTag
>   has a version number
>   when the asin is valid
>     match asin
>   amazon tag
>     #br2nl
>   invalid asin
>   Liquid Exception: ArgumentError in /Users/tokzk/gems/jekyll-amazon/tmp/source/_test/doc.md
>     raises an error
>   no asin
>   Liquid Exception: No ASIN given in amazon tag in /Users/tokzk/gems/jekyll-amazon/tmp/source/_test/doc.md
>     raises an error
> 
> Finished in 0.33686 seconds (files took 0.7212 seconds to load)
> 5 examples, 0 failures

**Comment by scottcwilson** [comment]
My apologies - I didn't realize you had to set 

> ECS_COUNTRY=us

 in the US.  

To get the output labels in English too, set 

> amazon_locale : en 

in the _config.yml file for the Jekyll project.
