### ISSUE TITLE
Please provide a way of overriding the detail method 

### ISSUE THREAD

**Issue by scottcwilson** [tokzk/jekyll-amazon#6]
I'd like to use detail, but only show image, author and title.  I know I can use display:none to hide the other attributes, but it would be nice if I could turn them off completely so the page would be smaller.  If you could allow us to specify what attributes were desired or otherwise allow detail to be overridden, that would be great.  Thank you!

**Comment by tokzk** [comment]
closed by ba6d99b Add support for custom template.

 _config.yml:
```
jekyll-amazon:
  template_dir: '_templates'
```

_templates/detail.erb:
```
<a href="<%= item[:detail_page_url] %>" target="_blank">
  <%= item[:title] %> / <%= item[:author] %>
</a>
```
